name: venv
channels:
  - pytorch
dependencies:
  - python=3.9
  - pip
  - pytorch
  - cudatoolkit=11.3
  - cudnn
  - conda-forge::tensorflow
  - anaconda::tensorflow-gpu
  - keras
  - scikit-learn
  - numpy
  - pandas
  - networkx
  - tqdm
  - pillow
  - boto3
  - h5py
  - pip:
    - opencv-python
    - config
